version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: taskhub-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: taskhub_db
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: