version: "3.9"
services:
  db:
    image: postgres:15
    container_name: smartloan_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: smartloan
      POSTGRES_PASSWORD: smartloanpwd
      POSTGRES_DB: smartloan
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: